import {after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {PrismaPg} from '@prisma/adapter-pg';
import {PrismaClient} from '../../src/generated/prisma/client';
import {utcDatabaseUrl} from '../../src/server/database-config';
import {adminLogin,adminLogout,adminSession} from '../../src/server/admin/auth';
import {saveAdminTheme} from '../../src/server/admin/preferences';
import {passwordHash} from '../../src/server/admin/password';
import {ADMIN_ACCOUNT_EMAIL} from '../../src/server/admin/account';
import {THEMES} from '../../src/lib/preferences';
const url=process.env.TEST_DATABASE_URL;
if(!url||process.env.LINA_ALLOW_DB_TESTS!=='1'||!['localhost','127.0.0.1'].includes(new URL(url).hostname)||!/^\/lina_test(?:_[a-z0-9_]+)?$/.test(new URL(url).pathname))throw Error('Disposable local DB required');
const db=new PrismaClient({adapter:new PrismaPg({connectionString:utcDatabaseUrl(url)})});
after(()=>db.$disconnect());
test('Admin theme defaults, whitelist, isolation, revoked session, login persistence',async()=>{
 const password=randomBytes(32).toString('hex');
 const a=await db.admin.upsert({where:{email:ADMIN_ACCOUNT_EMAIL},create:{email:ADMIN_ACCOUNT_EMAIL,displayName:'Test',passwordHash:await passwordHash(password)},update:{passwordHash:await passwordHash(password),disabledAt:null,uiTheme:'light'}});
 const b=await db.admin.create({data:{email:randomUUID()+'@example.invalid',displayName:'Other',passwordHash:await passwordHash(password)}});
 assert.equal(b.uiTheme,'light');
 await db.adminLoginThrottle.deleteMany();
 const session=await adminLogin(db,password);
 assert.equal((await adminSession(db,session.raw)).uiTheme,'light');
 for(const theme of THEMES)assert.deepEqual(await saveAdminTheme(db,session.raw,theme),{theme});
 assert.equal((await db.admin.findUniqueOrThrow({where:{id:b.id}})).uiTheme,'light');
 for(const bad of ['bad',null,{},'LIGHT'])await assert.rejects(saveAdminTheme(db,session.raw,bad),{status:400});
 await assert.rejects(saveAdminTheme(db,undefined,'coral'),{status:401});
 await assert.rejects(db.admin.update({where:{id:a.id},data:{uiTheme:'invalid'}}));
 await adminLogout(db,session.raw);
 await assert.rejects(saveAdminTheme(db,session.raw,'light'),{status:401});
 const fresh=await adminLogin(db,password);
 assert.equal((await adminSession(db,fresh.raw)).uiTheme,'coral');
 await db.adminSession.deleteMany({where:{adminId:a.id}});
 await db.admin.delete({where:{id:b.id}});
});
